import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-row bg-zinc-800`}>
        <aside className="flex bg-zinc-800 w-2/6">
          <Sidebar />
        </aside>
        <main className="flex">{children}</main>
      </body>
    </html>
  );
}
